// lib/mock-data.ts
// Single source of truth for all mock data — swap each export with a real API call later

import type { ScanRecord, Report, Notification, Tool, MockUser } from "./types";

// ─── USER ────────────────────────────────────────────────────────────────────
export const MOCK_USER: MockUser = {
  id: "usr_001",
  name: "Amina Marzak",
  email: "amina.marzak@cybelis.ma",
  initials: "AM",
  role: "Administrateur",
  plan: "Pro",
  joinedAt: "2026-01-15",
};

// ─── SCANS ───────────────────────────────────────────────────────────────────
export const MOCK_SCANS: ScanRecord[] = [
  {
    id: "scan_001",
    domain: "cybelis.ma",
    score: 72,
    status: "completed",
    date: "2026-07-08T14:22:00Z",
    duration: 124,
    critical: 1,
    high: 3,
    medium: 2,
    low: 1,
    modules: ["TLS", "DNS", "Headers", "Cookies"],
    vulnerabilities: [
      {
        id: "v001",
        title: "Certificat SSL expirant",
        description: "Le certificat SSL expire dans 12 jours. Renouvelez-le avant expiration.",
        severity: "critical",
        category: "TLS",
        remediation: "Renouveler le certificat via votre hébergeur ou Let's Encrypt.",
      },
      {
        id: "v002",
        title: "Header X-Frame-Options manquant",
        description: "La page est vulnérable aux attaques Clickjacking.",
        severity: "high",
        category: "Headers",
        remediation: "Ajouter `X-Frame-Options: DENY` dans la configuration du serveur.",
      },
      {
        id: "v003",
        title: "Content-Security-Policy absent",
        description: "Aucune CSP définie, exposant le site aux injections XSS.",
        severity: "high",
        category: "Headers",
        remediation: "Configurer une Content-Security-Policy stricte.",
      },
      {
        id: "v004",
        title: "Cookie sans flag HttpOnly",
        description: "Des cookies de session sont accessibles via JavaScript.",
        severity: "medium",
        category: "Cookies",
        remediation: "Ajouter le flag HttpOnly sur tous les cookies de session.",
      },
    ],
  },
  {
    id: "scan_002",
    domain: "hbsmanagement.com",
    score: 91,
    status: "completed",
    date: "2026-07-07T09:15:00Z",
    duration: 98,
    critical: 0,
    high: 0,
    medium: 1,
    low: 3,
    modules: ["TLS", "DNS", "Headers"],
    vulnerabilities: [
      {
        id: "v005",
        title: "Référence à une ancienne version TLS",
        description: "TLS 1.1 est encore autorisé en fallback.",
        severity: "medium",
        category: "TLS",
        remediation: "Désactiver TLS 1.0 et 1.1, n'autoriser que TLS 1.2 et 1.3.",
      },
    ],
  },
  {
    id: "scan_003",
    domain: "ecommerce-demo.ma",
    score: 48,
    status: "completed",
    date: "2026-07-05T18:40:00Z",
    duration: 210,
    critical: 3,
    high: 2,
    medium: 4,
    low: 2,
    modules: ["TLS", "DNS", "Headers", "Cookies", "Redirections"],
    vulnerabilities: [
      {
        id: "v006",
        title: "Certificat SSL expiré",
        description: "Le certificat SSL est expiré depuis 3 jours.",
        severity: "critical",
        category: "TLS",
        remediation: "Renouveler immédiatement le certificat SSL.",
      },
      {
        id: "v007",
        title: "HTTP non redirigé vers HTTPS",
        description: "Le site répond en HTTP sans redirection forcée.",
        severity: "critical",
        category: "Redirections",
        remediation: "Configurer une redirection 301 permanente de HTTP vers HTTPS.",
      },
      {
        id: "v008",
        title: "DNSSEC non configuré",
        description: "Le domaine est vulnérable aux attaques DNS spoofing.",
        severity: "critical",
        category: "DNS",
        remediation: "Activer DNSSEC sur votre registrar de domaine.",
      },
    ],
  },
  {
    id: "scan_004",
    domain: "stage-test.net",
    score: 85,
    status: "completed",
    date: "2026-06-29T11:05:00Z",
    duration: 87,
    critical: 0,
    high: 1,
    medium: 2,
    low: 0,
    modules: ["TLS", "Headers"],
    vulnerabilities: [
      {
        id: "v009",
        title: "Referrer-Policy non définie",
        description: "Les URLs sont exposées aux sites tiers via le header Referer.",
        severity: "high",
        category: "Headers",
        remediation: "Ajouter `Referrer-Policy: strict-origin-when-cross-origin`.",
      },
    ],
  },
  {
    id: "scan_005",
    domain: "startup-maroc.ma",
    score: 63,
    status: "completed",
    date: "2026-06-20T08:30:00Z",
    duration: 145,
    critical: 0,
    high: 2,
    medium: 3,
    low: 4,
    modules: ["TLS", "DNS", "Headers", "Cookies"],
    vulnerabilities: [],
  },
];

// ─── REPORTS ─────────────────────────────────────────────────────────────────
export const MOCK_REPORTS: Report[] = [
  {
    id: "rep_001",
    scanId: "scan_001",
    domain: "cybelis.ma",
    score: 72,
    status: "ready",
    createdAt: "2026-07-08T14:30:00Z",
    summary: "1 faille critique détectée. Action immédiate requise sur le certificat SSL.",
    critical: 1,
    high: 3,
    medium: 2,
    low: 1,
  },
  {
    id: "rep_002",
    scanId: "scan_002",
    domain: "hbsmanagement.com",
    score: 91,
    status: "ready",
    createdAt: "2026-07-07T09:25:00Z",
    summary: "Bonne posture de sécurité. 1 point d'attention sur TLS.",
    critical: 0,
    high: 0,
    medium: 1,
    low: 3,
  },
  {
    id: "rep_003",
    scanId: "scan_003",
    domain: "ecommerce-demo.ma",
    score: 48,
    status: "ready",
    createdAt: "2026-07-05T18:50:00Z",
    summary: "3 failles critiques. Intervention urgente requise.",
    critical: 3,
    high: 2,
    medium: 4,
    low: 2,
  },
  {
    id: "rep_004",
    scanId: "scan_004",
    domain: "stage-test.net",
    score: 85,
    status: "ready",
    createdAt: "2026-06-29T11:20:00Z",
    summary: "Site globalement sécurisé. Quelques ajustements de headers recommandés.",
    critical: 0,
    high: 1,
    medium: 2,
    low: 0,
  },
];

// ─── NOTIFICATIONS ────────────────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    title: "SSL critique",
    text: "Le certificat SSL de cybelis.ma expire dans 12 jours.",
    time: "Il y a 2h",
    read: false,
    type: "alert",
  },
  {
    id: 2,
    title: "Scan complété",
    text: "L'analyse de hbsmanagement.com est terminée. Score : 91/100",
    time: "Il y a 1 jour",
    read: false,
    type: "success",
  },
  {
    id: 3,
    title: "Nouveau rapport disponible",
    text: "Le rapport PDF pour ecommerce-demo.ma est prêt au téléchargement.",
    time: "Il y a 2 jours",
    read: true,
    type: "info",
  },
];

// ─── TOOLS ───────────────────────────────────────────────────────────────────
export const MOCK_TOOLS: Tool[] = [
  {
    id: "tool_tls",
    name: "Analyseur TLS/SSL",
    description: "Vérifie la validité du certificat, la version du protocole, et la chaîne de confiance.",
    category: "Sécurité réseau",
    status: "active",
    icon: "Lock",
  },
  {
    id: "tool_dns",
    name: "Analyse DNS",
    description: "Audite la configuration DNS : SPF, DMARC, DKIM, DNSSEC, et résolution des enregistrements.",
    category: "Infrastructure",
    status: "active",
    icon: "Globe",
  },
  {
    id: "tool_headers",
    name: "Headers HTTP",
    description: "Inspecte tous les en-têtes de sécurité HTTP : CSP, HSTS, X-Frame-Options, etc.",
    category: "Sécurité web",
    status: "active",
    icon: "Shield",
  },
  {
    id: "tool_cookies",
    name: "Audit Cookies",
    description: "Vérifie les flags HttpOnly, Secure, SameSite et les durées de vie des cookies.",
    category: "Sécurité web",
    status: "active",
    icon: "Cookie",
  },
  {
    id: "tool_redirects",
    name: "Redirections HTTP",
    description: "Détecte les boucles de redirection et vérifie les redirections HTTP→HTTPS.",
    category: "Infrastructure",
    status: "active",
    icon: "ArrowRight",
  },
  {
    id: "tool_ports",
    name: "Scan de Ports",
    description: "Détecte les ports ouverts inutilement exposés sur le serveur web.",
    category: "Sécurité réseau",
    status: "beta",
    icon: "Network",
  },
  {
    id: "tool_subdomains",
    name: "Sous-domaines",
    description: "Enumère les sous-domaines exposés et détecte les sous-domaines fantômes.",
    category: "Reconnaissance",
    status: "beta",
    icon: "GitBranch",
  },
  {
    id: "tool_leaks",
    name: "Détecteur de Fuites",
    description: "Recherche des informations sensibles exposées publiquement (emails, tokens, clés).",
    category: "Reconnaissance",
    status: "coming_soon",
    icon: "Search",
  },
];

// ─── SCAN MODULES (for the scan form) ────────────────────────────────────────
export const SCAN_MODULES = [
  { id: "tls", label: "TLS / SSL", description: "Certificat et protocole" },
  { id: "dns", label: "DNS", description: "SPF, DMARC, DKIM, DNSSEC" },
  { id: "headers", label: "Headers HTTP", description: "En-têtes de sécurité" },
  { id: "cookies", label: "Cookies", description: "Flags et attributs" },
  { id: "redirections", label: "Redirections", description: "HTTP → HTTPS" },
  { id: "ports", label: "Ports ouverts", description: "Exposition réseau" },
];
